sass:
  tasks:
    public:
      src:
        - 'assets/sass/**/*.scss'
      dst: 'static/assets/css'
  settings:
    sass:
      errLogToConsole: true
    inlineSVG:
      path: 'assets/'
    extractMQ: false
    critical: false
    purgeCSS: false
